name: Build OpenWrt-6220
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@main
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
